Allow `discard_init_args_on_class_path_change` to handle more nested contexts
omni-us/jsonargparse pull request #248
Opened 2023-02-23 06:05 UTC by speediedan

## What does this PR do?

Fixes #247 

While a ``subclass_spec`` can be either a ``dict`` or ``Namespace`` 
https://github.com/omni-us/jsonargparse/blob/ac790ba09bcc920cab1acf712422152b931d337a/jsonargparse/typehints.py#L790-L795
when entering ``ActionTypeHint.discard_init_args_on_class_path_change``:
https://github.com/omni-us/jsonargparse/blob/ac790ba09bcc920cab1acf712422152b931d337a/jsonargparse/typehints.py#L295-L310

``jsonargparse.typehints.discard_init_args_on_class_path_change`` below currently assumes any previous value for a nested subclass will already have been cast as a ``Namespace``: 
https://github.com/omni-us/jsonargparse/blob/ac790ba09bcc920cab1acf712422152b931d337a/jsonargparse/typehints.py#L934-L942

with ``L941`` resulting in:
```
argparse.ArgumentError: Parser key "some_class":
  Problem with given class_path '__main__.CustomModule':
    - 'dict' object has no attribute 'init_args'
```
Right now, nested generic ``dict`` configurations like the repro case I include below don't trigger the ``subclass_spec_as_namespace`` ``Namespace`` wrapping that ``jsonargparse.typehints.discard_init_args_on_class_path_change`` requires when removing overridden subclass spec configuration in this context.

With this PR's minor patch to ``jsonargparse.typehints.discard_init_args_on_class_path_change``, this use case can be accommodated. This PR also adds a test that covers the expanded support.
```
## Before submitting

- [x] Did you read the [contributing guideline](https://github.com/omni-us/jsonargparse/blob/master/CONTRIBUTING.rst)?
- [x] Did you update **the documentation**? (readme and public docstrings)
- [x] Did you write **unit tests** such that there is 100% coverage on related code? (required for bug fixes and new features)
- [x] Did you verify that new and existing **tests pass locally**?
- [x] Did you make sure that all changes preserve **backward compatibility**?
- [x] Did you update **the CHANGELOG**? (not for typos, docs, test updates, or minor internal changes/refactors)

2023-03-07 11:12 UTC, mauvilsa requested changes
Sorry for not looking at this sooner. Thank you very much for contributing!

Please add an entry to the changelog.

2023-03-09 04:22 UTC, speediedan commented on jsonargparse/typehints.py
> +            prev_val = subclass_spec_as_namespace(prev_val)
> Sorry for not looking at this sooner. Thank you very much for contributing!
> 
> Please add an entry to the changelog.
Done. Happy to help, thanks again for maintaining this valuable package!

2023-03-09 04:24 UTC, speediedan commented on jsonargparse/typehints.py
> +            prev_val = subclass_spec_as_namespace(prev_val)
> Lets have this line without the `if`. When `prev_val` is already a namespace, that function works fine. There might be cases in which `prev_val` is a namespace and `init_args` a dict, which would be handled by not having the `if`.

Makes sense!

2023-03-09 09:46 UTC, mauvilsa approved these changes

2023-03-09 09:47 UTC, merged