Feature path std io
omni-us/jsonargparse pull request #475
Opened 2024-03-18 10:05 UTC by mquillot

## What does this PR do?

Add support for "-" as value for Path class initialization so that user
can ask to use standard input/output instead of file.

For instance, users who are used to type their input files with Path_fr will now be able to give "-" as input string so that get_content or open (of Path_fr class) will read the standard input stream without having nothing more to do. Same for output.

Note that some code has been added for typehiting so that it does not create conflict with another feature: giving "-" to specify that a list of files is given through the standard input.

## Before submitting

- [ X ] Did you read the [contributing guideline](https://github.com/omni-us/jsonargparse/blob/main/CONTRIBUTING.rst)?
- [ X ] Did you update **the documentation**? (readme and public docstrings)
- [ X ] Did you write **unit tests** such that there is 100% coverage on related code? (required for bug fixes and new features)
- [ X ] Did you verify that new and existing **tests pass locally**?
- [ X ] Did you make sure that all changes preserve **backward compatibility**?
- [ X ] Did you update **the CHANGELOG**? (not for typos, docs, test updates, or minor internal changes/refactors)

2024-03-19 09:03 UTC, mauvilsa requested changes
Overall it looks very good. Thank you! Thought I do want some changes.

2024-03-19 09:03 UTC, mauvilsa commented on jsonargparse_tests/test_util.py
> +    assert path.std_io
Remove these. No point with empty mode or with just "w".

2024-03-19 09:03 UTC, mauvilsa commented on jsonargparse_tests/test_util.py
> +    with patch("sys.stdout", StringIO("")):
Save the `StringIO` instance to a variable, and after the write, assert that the content of the `StringIO` is what got printed.

2024-04-03 10:21 UTC, mquillot commented
I think @mauvilsa you can review a second time. I tried to follow you recommandations as soon as possible.

2024-04-03 10:22 UTC, mquillot commented on jsonargparse/_typehints.py
> +                        raise ex
Ok, I let you propose a modification?

2024-04-03 10:22 UTC, mquillot commented on jsonargparse/_util.py
> +                yield sys.stdout
I let you propose a modification?

2024-04-05 20:11 UTC, mauvilsa commented on jsonargparse/_util.py
> +                yield sys.stdout
No proposal. I just noticed this. But I am not sure how much of a problem would it be. Lets just leave it like this and only do something about it if it creates a problem for someone.

2024-04-05 20:12 UTC, mauvilsa commented on jsonargparse/_typehints.py
> +                        raise ex
I don't yet know. We can leave it like this here, but will take a note to look at this later.

2024-04-05 20:13 UTC, mauvilsa approved these changes
Looks good!

2024-04-05 20:13 UTC, merged