Fix tests inside of docker
omni-us/jsonargparse pull request #573
Opened 2024-09-12 16:50 UTC by Erotemic

I've run into a tricky issue when running tests locally inside of a docker environment. Tests that involved changing permissions to make a file unreadable were failing when I ran them inside of docker, but they worked on my host system. After a bit of thinking I realized this was because the default user in docker is root, which means files can be read even if they are unreadable according to the permissions.

To address this, I made two changes:
* In test_core, I check if I can still read the file after it is forced to be unreadable. If it can be, then we can assume we are in some special circumstance, and we should skip the test.

* In test_util, it looks like there is a custom path object, so I fell back to just checking if `os.geteuid() == 0`, which should only be true on linux for the root user. In this case I skip the test.

Because this is only a test change, I'm not sure if you want a changelog entry.

2024-09-13 05:02 UTC, mauvilsa commented
Running tests as root doesn't sound like a great idea. Better to use a real user so that the tests are run in an environment closer to how the code will be used later. And if you want to run the tests, skipping tests shouldn't be the go to solution.

I would recommend that you run the tests as a non-root user. In docker it is easy to switch user. If for some reason you really don't want to do that, from the command line you can tell pytest to skip some tests. No need to change the code.
```
pytest -k "not <test-name-1> and not <test-name-2> ..."
```

2024-09-13 14:46 UTC, Erotemic commented
Yes, it is better to use a real use. Unfortunately, running as root in docker is the de-facto standard. Do I like it? No. But it is the reality.

I feel that just running `pytest` in the repo should "just work" in reasonable circumstances. But I also feel I'm going to have no success in arguing a point here. :face_exhaling:

2024-09-13 15:59 UTC, mauvilsa commented
I have no problem in accepting this pull request. If you really want to go ahead a run tests as root, I can comment a couple of things and later we merge it.

But a clarification. Running tests as root is not a standard. The tests run here via circle ci all use docker images. They run as non-root and I didn't anything special for this. Maybe the github tests also run in docker containers, I am not sure, but if they do, then they run as non-root by default.

Base docker images do come as default as root. Though, the idea is that layers are added on top and the user changed. It is a good practice to never run docker containers as root.

2024-09-13 16:04 UTC, mauvilsa requested changes

2024-09-13 16:04 UTC, mauvilsa commented on jsonargparse_tests/test_util.py
> +        pytest.skip("User is root, skipping permission tests")
Please skip using a decorator, similar to https://github.com/omni-us/jsonargparse/blob/1bab38ae7a5fe281c62fe784fc620bbbf259f2e8/jsonargparse_tests/conftest.py#L35-L38

2024-09-13 16:04 UTC, mauvilsa commented on jsonargparse_tests/test_core.py
> +        pytest.skip("File was still readable even after chmod(0)")
Please skip the entire test function using a decorator, instead of this try-except block.

2024-09-13 16:04 UTC, mauvilsa commented on jsonargparse_tests/test_core.py
> +        pytest.skip("File was still readable after chmod(0)")
Please skip the entire test function using a decorator, instead of this try-except block.

2024-09-13 20:32 UTC, Erotemic commented
> If you really want to go ahead a run tests as root, I can comment a couple of things and later we merge it.

Thanks. I wish running as non-root was an option, but I'm working in an environment where everything is running on a base `python:3.11` image and there is little-to-no opportunity to change that. Others will install their packages to hard coded paths (e.g. `/root/<theirstuff>`) so if I swapped out the shared base image for something with a builtin non-root user then that would cause breakage. For better or worse I'm stuck in this environment, and this isn't the first time I've worked in a team where root-user docker images was the norm. For my part, I just want to be able to run through test suites (and show others how to run through the tests suites) with an invocation of `pytest`.

Having a root-user environment certainly isn't a problem for professional CI systems, but when working on teams with developers at many different skill levels, it can and does come up. I appreciate your willingness to help me out by adding code to detect and work around this admittedly non-ideal enviornment.

2024-09-16 05:07 UTC, mauvilsa approved these changes

2024-09-16 05:07 UTC, merged