fix: empty tuples are correctly parsed
omni-us/jsonargparse pull request #592
Opened 2024-10-06 16:57 UTC by MiguelMonteiro

## What does this PR do?

Empty tuples are now successfully parsed.

## Before submitting

- [ ] Did you read the [contributing guideline](https://github.com/omni-us/jsonargparse/blob/main/CONTRIBUTING.rst)?
- [ ] Did you update **the documentation**? (readme and public docstrings)
- [x] Did you write **unit tests** such that there is 100% coverage on related code? (required for bug fixes and new features)
- [x] Did you verify that new and existing **tests pass locally**?
- [x] Did you make sure that all changes preserve **backward compatibility**?
- [ ] Did you update **the CHANGELOG**? (not for typos, docs, test updates, or minor internal changes/refactors)

2024-10-07 05:21 UTC, mauvilsa requested changes

2024-10-07 05:21 UTC, mauvilsa commented on jsonargparse/_typehints.py
> -                raise_unexpected_value("Expected a non-empty tuple", val)
Don't remove the raise for empty tuple. This is correct and necessary. Only tuples with `...` should be allowed to be empty. But other tuples not. The code here should be:
```python
if is_tuple and len(val) == 0 and not is_ellipsis:
    raise_unexpected_value("Expected a non-empty tuple", val)
```

2024-10-07 06:48 UTC, mauvilsa commented on jsonargparse/_typehints.py
> -                raise_unexpected_value("Expected a non-empty tuple", val)
Actually no. These two lines should be removed. Number of elements in the tuple are already handled by
```python
if is_tuple and not is_ellipsis and len(val) != len(subtypehints):
    raise_unexpected_value(f"Expected a tuple with {len(subtypehints)} elements", val)
```
And converting the empty list to a tuple would already be handled by
```python
if not serialize:
    val = tuple(val) if typehint_origin in {Tuple, tuple} else set(val)
```

2024-10-07 21:19 UTC, mauvilsa requested changes
Also please add a changelog entry in a new section as explained in the contributions guide.

2024-10-09 14:44 UTC, MiguelMonteiro commented
Thank you for the feedback, I have made the requested changes, let me know if it's correct.

2024-10-09 15:19 UTC, mauvilsa requested changes

2024-10-09 15:19 UTC, mauvilsa commented on CHANGELOG.rst
> +v4.33.3 (2024-10-09)
```suggestion
v4.33.3 (2024-10-??)
```

2024-10-09 15:27 UTC, merged